shell = "zsh"

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
hooks.post = '''
zsh-defer source $ZSHRC_DIR/lazy.zsh
zsh-defer -t 0.001 autoload -Uz compinit
zsh-defer -t 0.001 compinit
'''

[plugins.zsh-git-prompt]
github = 'olivierverdier/zsh-git-prompt'
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ["defer"]

[plugins.git-open]
github = 'paulirish/git-open'
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ["defer"]

[plugins.zsh-completion]
github = 'zsh-users/zsh-completions'
apply = ["defer"]

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'
# use = ['{{ name }}.zsh-theme']
hooks.pre = '''
ZLE_PROMPT_INDENT=0
source $ZSHRC_DIR/plugrc/p10k.zsh
'''

[plugins.zeno]
github = 'yuki-yano/zeno.zsh'
use = ['zeno.zsh']
apply = ['defer']
hooks.pre = 'zsh-defer $ZSHRC_DIR/plugrc/zeno_atinit.zsh'
hooks.post = '''
zsh-defer source $ZSHRC_DIR/plugrc/zeno_atload.zsh
'''

